// <auto-generated />
using GS_SpaceConnect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GS_SpaceConnect.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260608184518_AdicionarPropriedadeRural")]
    partial class AdicionarPropriedadeRural
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GS_SpaceConnect.Models.AnaliseAgricola", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Luminosidade")
                        .HasColumnType("double");

                    b.Property<string>("NomeSensor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Temperatura")
                        .HasColumnType("double");

                    b.Property<double>("Umidade")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("AnaliseAgricolas");
                });

            modelBuilder.Entity("GS_SpaceConnect.Models.PropriedadeRural", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Regiao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PropriedadesRurais");
                });
#pragma warning restore 612, 618
        }
    }
}
